[0m18:07:37.014110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e9d090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cf5de0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cf5990>]}


============================== 18:07:37.016516 | da70ead3-1aa5-4c1c-b579-c23935fcd69b ==============================
[0m18:07:37.016516 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:07:37.016831 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/raghav/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:07:37.024151 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/Users/raghav/.dbt')}
[0m18:07:37.024356 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:08:19.201399 [debug] [MainThread]: Starter project path: /Users/raghav/.pyenv/versions/3.10.16/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:08:19.215145 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:08:19.217394 [info ] [MainThread]: Setting up your profile.
[0m18:12:12.506533 [info ] [MainThread]: Profile custom_postgres written to /Users/raghav/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:12:12.558407 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 275.58002, "process_in_blocks": "0", "process_kernel_time": 0.119688, "process_mem_max_rss": "92078080", "process_out_blocks": "0", "process_user_time": 0.576805}
[0m18:12:12.559477 [debug] [MainThread]: Command `dbt init` succeeded at 18:12:12.559279 after 275.58 seconds
[0m18:12:12.560327 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e9d090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cf6ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109242b90>]}
[0m18:12:12.561099 [debug] [MainThread]: Flushing usage events
[0m18:12:13.024670 [debug] [MainThread]: An error was encountered while trying to flush usage events
